Explicit error when a field/module is not found
Occurring when assembly A depends on B & C and B also depends on C (v2)
if a field has been renamed in C and is used in B, it won't be found.
Displays:
 NullReferenceException: Field "my.namespace.MyType my.namespace.MyType
::MyField" not found in type "my.namespace.MyType".
Instead of:
 InvalidOperationException: Sequence contains no matching element